name: VanishTP
description: Returns players to the location at which they vanished once they unvanish.
author: DintyB
main: io.github.dinty1.vanishtp.VanishTP
version: ${project.version}
api-version: 1.16
depend: [SuperVanish]
permissions:
  vanishtp.preventteleport:
    description: Prevents the player from being teleported after unvanishing.
    default: op